adjective1 = input("Enter an adjective(a description of something): ")
noun1 = input("Enter a noun(person,place or thing): ")
adjective2 = input("Enter an adjective(a description of something): ")
verb1 = input("Enter a verb ending with ing: ")
adjective3 = input("Enter an adjective(a description of something): ")

print(f"Today I went to a {adjective1} zoo")
print(f"In an exhibit I saw a {noun1}")
print(f"{noun1} was {adjective2} and {verb1}")
print(f"I was {adjective3}!")